const errorTypes = {
  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_LOGIN: "INVALID_LOGIN",
  INVALID_EMAIL: "INVALID_EMAIL",
  REGISTER_INCOMPLETE: "REGISTER_INCOMPLETE",
  DUPLICATE_KEY: "DUPLICATE_KEY",
  DUPLICATE_PHONE_NUMBER: "DUPLICATE_PHONE_NUMBER"
};
export default errorTypes;
