const requerimientsTypes = {
  IDENTITY_VALIDATION: "IDENTITY_VALIDATION",
  ADDITIONAL_INFORMATION: "ADDITIONAL_INFORMATION",
  BANK_ACCOUNT: "BANK_ACCOUNT",
  ACCOUNT_VALIDATION: "ACCOUNT_VALIDATION"
};
export default requerimientsTypes;
